# Generated by Django 5.2.6 on 2025-09-12 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='keywords',
            new_name='skills',
        ),
    ]
